/*************************** Melp***********************/
const GET_MELP_RESTAURANTS_DATA = 'pages/home/GET_MELP_RESTAURANT_DATA';
const GET_MELP_RESTAURANTS_DATA_ERROR = 'pages/home/GET_MELP_RESTAURANT_DATA_ERROR';
const GET_MELP_RESTAURANTS_DATA_SUCCESS = 'pages/home/GET_MELP_RESTAURANT_DATA_SUCCESS';
const SET_ACTIVE_CATEGORIE = 'components/Tabs/TabItem/SET_ACTIVE_CATEGORIE';
const SET_SORTED_DATA = 'components/SortDropdown/SortDropdown/SET_SORTED_DATA';

export {
  GET_MELP_RESTAURANTS_DATA,
  GET_MELP_RESTAURANTS_DATA_ERROR,
  GET_MELP_RESTAURANTS_DATA_SUCCESS,
  SET_ACTIVE_CATEGORIE,
  SET_SORTED_DATA,
};
