/*************************** Melp***********************/
const GET_MELP_RESTAURANTS_DATA = 'pages/home/GET_MELP_RESTAURANT_DATA';
const GET_MELP_RESTAURANTS_DATA_ERROR = 'pages/home/GET_MELP_RESTAURANT_DATA_ERROR';
const GET_MELP_RESTAURANTS_DATA_SUCCESS = 'pages/home/GET_MELP_RESTAURANT_DATA_SUCCESS';
const SET_ACTIVE_CATEGORIE = 'components/tabItem/SET_ACTIVE_CATEGORIE';

export {
  GET_MELP_RESTAURANTS_DATA,
  GET_MELP_RESTAURANTS_DATA_ERROR,
  GET_MELP_RESTAURANTS_DATA_SUCCESS,
  SET_ACTIVE_CATEGORIE,
};
